name: Docker Build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image with all binaries
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            PACKAGE_NAMES=users-service,articles-service,axum-otel-demo
          push: false
          tags: tracing-otel-extra-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build users service runtime
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.users
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/users:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/users:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build articles service runtime
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.articles
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/articles:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/articles:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build otel example runtime
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.demo
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/axum-otel-demo:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/axum-otel-demo:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
